---
- name: Create Kubernetes Cluster with KOPS
  hosts: master
  become: yes
  vars:
    aws_region: "us-east-2"
    kops_state_bucket: "debby-kops-state-bucket"
    dns_zone: "debbyboyofinal.com"
    cluster_name: "debbyboyofinal.com"
    zones: "us-east-2a,us-east-2b"
    node_count: 2
    node_size: "t2.small"
    control_plane_size: "t2.small"

  tasks:

  - name: Ensure environment variables are exported permanently
    lineinfile:
      path: ~/.bashrc
      line: "{{ item }}"
      create: yes
    loop:
      - "export KOPS_STATE_STORE=s3://{{ kops_state_bucket }}"
      - "export AWS_DEFAULT_REGION={{ aws_region }}"

  - name: Source environment variables for this session
    shell: |
      export KOPS_STATE_STORE=s3://{{ kops_state_bucket }}
      export AWS_DEFAULT_REGION={{ aws_region }}
      kops create cluster \
        --name={{ cluster_name }} \
        --dns-zone={{ dns_zone }} \
        --zones={{ zones }} \
        --state=s3://{{ kops_state_bucket }} \
        --node-count={{ node_count }} \
        --node-size={{ node_size }} \
        --control-plane-size={{ control_plane_size }} \
        --yes
    environment:
      KOPS_STATE_STORE: "s3://{{ kops_state_bucket }}"
      AWS_DEFAULT_REGION: "{{ aws_region }}"
