---
- name: Create Kubernetes Cluster using KOPS
  hosts: k8s_master
  become: yes
  tasks:

    - name: Create Kubernetes cluster with KOPS
  shell: |
    export KOPS_STATE_STORE=s3://debby-kops-state-bucket
    export AWS_DEFAULT_REGION=us-east-2
    kops create cluster \
      --name=debbyboyofinal.com \
      --dns-zone=debbyboyofinal.com \
      --zones=us-east-2a,us-east-2b \
      --state=s3://debby-kops-state-store \
      --node-count=2 \
      --node-size=t2.small \
      --control-plane-size=t2.small \
      --yes
      
  environment:
        KOPS_STATE_STORE: s3://debby-kops-state-store
        AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        register: kops_output

- name: Print KOPS output
        debug:
        var: kops_output.stdout_lines
