---
- name: Create Kubernetes Cluster using KOPS
  hosts: k8s_master
  become: yes
  tasks:

    - name: Set environment variables for KOPS
      shell: |
        export KOPS_STATE_STORE=s3://debby-kops-state-store
        export AWS_DEFAULT_REGION=us-east-2
        kops create cluster \
          --name=debbyboyofinal.com \
          --dns-zone=debbyboyofinal.com \
          --zones=us-east-2a,us-east-2b \
          --state=s3://debby-kops-state-store \
          --node-count=2 \
          --node-size=t2.small \
          --control-plane-size=t2.small \
          --yes
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
      register: kops_output

    - name: Print KOPS output
      debug:
        var: kops_output.stdout_lines
