---
- name: Create Kubernetes Cluster with Kops
  hosts: k8s_master
  become: yes
  vars:
    kops_state_store: s3://debby-kops-final-state-bucket
    cluster_name: debbyboyofinal.k8s.local
    aws_region: us-east-2
    zones: us-east-2a,us-east-2b
    node_size: t2.small
    control_plane_size: t2.small
    node_count: 2

  tasks:
    - name: Set environment variables and create cluster
      shell: |
        export AWS_DEFAULT_REGION={{ aws_region }}
        export KOPS_STATE_STORE={{ kops_state_store }}

        kops create cluster \
          --name={{ cluster_name }} \
          --zones={{ zones }} \
          --state={{ kops_state_store }} \
          --node-count={{ node_count }} \
          --node-size={{ node_size }} \
          --control-plane-size={{ control_plane_size }} \
          --dns=none \
          --yes
      args:
        executable: /bin/bash
      register: kops_output
      ignore_errors: false

    - name: Show Kops output
      debug:
        var: kops_output.stdout_lines
