---
- name: Install Kubernetes tools on Workstation
  hosts: k8s_master
  become: true
  tasks:
    - name: Install AWS CLI
      yum:
        name: awscli
        state: present

    - name: Install kubectl
      get_url:
        url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.5/2023-11-14/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Download kubectl binary
  get_url:
    url: "https://dl.k8s.io/release/v1.28.5/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

